spring:
  datasource:
    url: jdbc:mysql://112.74.189.206:3309/test?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    data-username: root
    data-password: 123456
  task:
    scheduling:
      pool:
        size: 20
    execution:
      pool:
        max-size: 20
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
server:
  port: 8001
